language: java
jdk:
  - openjdk16
before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker pull openjdk:16-jre-slim-sid
  - chmod +x mvnw
script:
  - ./mvnw clean install
  - ./mvnw deploy jib:build -P deploy-docker8