spring:
  devtools:
    add-properties: true
  mvc:
    log-request-details: true

    # App Properties
wasser:
  jwtExpirationMs: 86400000
  jwtSecret: bezKoderSecretKey

logging:
  level:
    org:
      springframework:
        http:
          converter:
            json:
              Jackson2ObjectMapperBuilder: DEBUG
