version: "3"

services:
  mariadb:
    image: "mariadb:latest"
    restart: 'always'
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "wasser"
      MYSQL_USER: "wasser"
      MYSQL_PASSWORD: "wasser"